export const DUMMY_CHATS = [
  {
    id: "1",
    name: "Darrell Steward",
    avatar: "https://i.pravatar.cc/150?u=1",
    avatarType: "image",
    lastMessage: "Hello, Good morning ✨",
    time: "11:47 PM",
    unreadCount: 4,
    isPinned: false,
    isActive: true,
  },
  {
    id: "2",
    name: "Jane Cooper",
    avatarType: "initials",
    initials: "JC",
    avatarColor: "#F59E0B", // amber-500
    lastMessage: "You: Can you sent the photo?",
    time: "11:23 PM",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
  {
    id: "3",
    name: "Theresa Webb",
    avatar: "https://i.pravatar.cc/150?u=3",
    avatarType: "image",
    lastMessage: "Okay, Thank you",
    time: "11:17 PM",
    unreadCount: 4,
    isPinned: false,
    isActive: false,
  },
  {
    id: "4",
    name: "Work Team",
    avatarType: "group",
    avatarColor: "#1E3A8A", // blue-900
    lastMessage: "Wait, I am on my way!",
    time: "08:26 PM",
    unreadCount: 0,
    isPinned: true,
    isActive: true,
  },
  {
    id: "5",
    name: "Annette Black",
    avatar: "https://i.pravatar.cc/150?u=5",
    avatarType: "image",
    lastMessage: "You: Okay Rin, sounds good. Let's...",
    time: "08:13 PM",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
  {
    id: "6",
    name: "Ronald Richards",
    avatarType: "initials",
    initials: "RR",
    avatarColor: "#8B5CF6", // violet-500
    lastMessage: "You: Can you sent the photo?",
    time: "Yesterday",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
  {
    id: "7",
    name: "Guy Hawkins",
    avatar: "https://i.pravatar.cc/150?u=7",
    lastMessage: "Okay, Thank you",
    time: "Yesterday",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
  {
    id: "8",
    name: "Eleanor Pena",
    avatar: "https://i.pravatar.cc/150?u=8",
    lastMessage: "Sounds like a plan! 🚀",
    time: "Monday",
    unreadCount: 1,
    isPinned: false,
    isActive: true,
  },
  {
    id: "9",
    name: "Cody Fisher",
    avatar: "https://i.pravatar.cc/150?u=9",
    lastMessage: "I will send it over later.",
    time: "Sunday",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
  {
    id: "10",
    name: "Esther Howard",
    avatar: "https://i.pravatar.cc/150?u=10",
    lastMessage: "You: Where are you right now?",
    time: "Oct 12",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
  {
    id: "11",
    name: "Jenny Wilson",
    avatar: "https://i.pravatar.cc/150?u=11",
    lastMessage: "Thanks for your help!",
    time: "Oct 11",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
  {
    id: "12",
    name: "Kristin Watson",
    avatar: "https://i.pravatar.cc/150?u=12",
    lastMessage: "Are we still on for tomorrow?",
    time: "Oct 10",
    unreadCount: 2,
    isPinned: false,
    isActive: true,
  },
  {
    id: "13",
    name: "Jacob Jones",
    avatar: "https://i.pravatar.cc/150?u=13",
    lastMessage: "I loved the new update.",
    time: "Oct 9",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
  {
    id: "14",
    name: "Ralph Edwards",
    avatar: "https://i.pravatar.cc/150?u=14",
    lastMessage: "You: Let me know what you think.",
    time: "Oct 8",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
  {
    id: "15",
    name: "Courtney Henry",
    avatar: "https://i.pravatar.cc/150?u=15",
    lastMessage: "Can we reschedule?",
    time: "Oct 5",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
];

export const DUMMY_MESSAGES = [
  {
    id: "m1",
    text: "Habitant elit pellentesque curabitur morbi sit fusce elit",
    time: "18:25",
    isMe: false,
  },
  {
    id: "m2",
    text: "Gravida lectus semper orci",
    time: "19:40",
    isMe: true,
  },
  {
    id: "m3",
    text: "Egestas interdum orci commodo faucibus pretium, neque etiam",
    time: "19:40",
    isMe: false,
  },
  {
    id: "m4",
    text: "Orci maecenas hendrerit mattis consectetur. Mauris.",
    time: "19:40",
    isMe: false,
  },
  {
    id: "m5",
    text: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    time: "19:42",
    isMe: true,
  },
  {
    id: "m6",
    text: "Nulla facilisi. Nullam in magna id.",
    time: "19:43",
    isMe: false,
  },
  {
    id: "m7",
    text: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    time: "19:45",
    isMe: true,
  },
  {
    id: "m8",
    text: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    time: "19:46",
    isMe: false,
  },
  {
    id: "m9",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    time: "19:50",
    isMe: true,
  },
  {
    id: "m10",
    text: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    time: "19:51",
    isMe: false,
  },
  {
    id: "m11",
    text: "Yes, I agree completely.",
    time: "19:55",
    isMe: true,
  },
  {
    id: "m12",
    text: "Let me check and get back to you.",
    time: "19:56",
    isMe: false,
  },
  {
    id: "m13",
    text: "Take your time!",
    time: "19:57",
    isMe: true,
  },
  {
    id: "m14",
    text: "I found the document you mentioned.",
    time: "20:05",
    isMe: false,
  },
  {
    id: "m15",
    text: "Awesome, please send it over.",
    time: "20:06",
    isMe: true,
  },
  {
    id: "m16",
    text: "Here it is. Let me know if you have any questions.",
    time: "20:07",
    isMe: false,
  },
  {
    id: "m17",
    text: "Got it. I will review it tonight.",
    time: "20:10",
    isMe: true,
  },
  {
    id: "m18",
    text: "Great! Have a good evening.",
    time: "20:12",
    isMe: false,
  },
];

export const DUMMY_ARCHIVED_CHATS = [
  {
    id: "a1",
    name: "Annie Miles",
    avatar: "https://i.pravatar.cc/150?u=a1",
    avatarType: "image",
    lastMessage: "Please, I don't know anything ab...",
    time: "20:46 PM",
    unreadCount: 2,
    isPinned: false,
    isActive: false,
  },
  {
    id: "a2",
    name: "Arlene McCoy",
    avatar: "https://i.pravatar.cc/150?u=a2",
    avatarType: "image",
    lastMessage: "Wow, it's very cool",
    time: "11:23 PM",
    unreadCount: 0,
    isPinned: false,
    isActive: false,
  },
];
